[project]
name = "lection-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandantic>=1.0.1",
    "rich>=14.2.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
